<a href="https://colab.research.google.com/github/access-dinesh/DS_Python/blob/main/Tensors_17022024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [9]:
mylist=[1,2,3,4,5]
mylist

[1, 2, 3, 4, 5]

In [10]:
mylist1=[[1,2,3,4,5],[6,7,8,9,10]]
mylist1

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [22]:
np1 = np.random.rand(3)
np1

array([0.22179066, 0.35119585, 0.83498248])

In [24]:
np1.dtype

dtype('float64')

In [23]:
np2 = np.random.rand(3,4)
np2

array([[0.78096274, 0.21336518, 0.27381313, 0.2955847 ],
       [0.83601792, 0.30286541, 0.49207246, 0.98106477],
       [0.22825855, 0.00807266, 0.27045832, 0.86662329]])

In [25]:
np3 = np.random.rand(3,4,5)
np3

array([[[0.04906607, 0.43605465, 0.93969354, 0.00671774, 0.36062098],
        [0.10657189, 0.01329479, 0.08071855, 0.29871877, 0.37888505],
        [0.22752546, 0.73462369, 0.00456284, 0.07267468, 0.34931606],
        [0.52103315, 0.28369512, 0.59588645, 0.54884391, 0.13439222]],

       [[0.49854457, 0.76986296, 0.00659152, 0.31003727, 0.25798367],
        [0.34755749, 0.49080699, 0.73574473, 0.44714914, 0.89857894],
        [0.61503273, 0.45359341, 0.08015253, 0.08223578, 0.80194662],
        [0.21449458, 0.15493051, 0.72357491, 0.63898109, 0.63332286]],

       [[0.83339973, 0.67898328, 0.92689935, 0.48471043, 0.52305523],
        [0.09510595, 0.28368506, 0.02220803, 0.12245197, 0.23326632],
        [0.18780676, 0.77316971, 0.93109192, 0.68905261, 0.89202086],
        [0.08180276, 0.88192092, 0.38291911, 0.54498059, 0.68765544]]])

In [27]:
tensor1 = torch.randn(3)
tensor1

tensor([-1.3333,  1.2562,  0.1860])

In [28]:
tensor1.dtype

torch.float32

In [29]:
tensor2 = torch.randn(3,4)
tensor2

tensor([[ 0.2524, -0.4779,  0.8547, -0.6926],
        [-1.5194,  0.1643, -0.7216,  0.3639],
        [-0.6160, -0.7803,  0.3334,  1.0757]])

In [30]:
tensor3=torch.zeros(3,4)
tensor3

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
tensor4 = torch.tensor(np3)
tensor4

tensor([[[0.0491, 0.4361, 0.9397, 0.0067, 0.3606],
         [0.1066, 0.0133, 0.0807, 0.2987, 0.3789],
         [0.2275, 0.7346, 0.0046, 0.0727, 0.3493],
         [0.5210, 0.2837, 0.5959, 0.5488, 0.1344]],

        [[0.4985, 0.7699, 0.0066, 0.3100, 0.2580],
         [0.3476, 0.4908, 0.7357, 0.4471, 0.8986],
         [0.6150, 0.4536, 0.0802, 0.0822, 0.8019],
         [0.2145, 0.1549, 0.7236, 0.6390, 0.6333]],

        [[0.8334, 0.6790, 0.9269, 0.4847, 0.5231],
         [0.0951, 0.2837, 0.0222, 0.1225, 0.2333],
         [0.1878, 0.7732, 0.9311, 0.6891, 0.8920],
         [0.0818, 0.8819, 0.3829, 0.5450, 0.6877]]], dtype=torch.float64)

In [33]:
tensor4.dtype

torch.float64